[project]
name = "intern"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[all]>=0.136.3",
    "psycopg2>=2.9.12",
    "psycopg2-binary>=2.9.12",
    "sqlalchemy>=2.0.50",
    "pytest (>=9.0.3,<10.0.0)",
    "testcontainers (>=4.14.2,<5.0.0)",
]
